color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.277638
  lightness: 0.27944
  rhythmicContrast: 0.977748
  saturation: 0.802374
layout_spectrum: 0.247532
name: Hosham
typography_spectrum: 0.905427
