color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 1
  lightness: 0.680098
  rhythmicContrast: 0.895559
  saturation: 0.84375
layout_spectrum: 0.247532
name: Hosham
typography_spectrum: 0.905427
